// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmxgrowxqrtsdqlaypio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtteGdyb3d4cXJ0c2RxbGF5cGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNjUxNTEsImV4cCI6MjA1MzY0MTE1MX0.MDdH-PiaTR8YGtCzWcX7oCWwF4H8RH0YKTikNJhU1GU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);